services:
  if_ms_redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    container_name: cf_ms_redis
    networks:
      - mailnet
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_cache:/data

  if_ms_php:
    build:
      args:
        user: ${SYSUSER}
        uid: ${SYSID}
      context: ./containers/php/8.2
      dockerfile: Dockerfile
    image: if_ms_php
    container_name: cf_ms_php
    restart: always
    working_dir: /var/www/
    env_file:
      - ./.env
    volumes:
      - ./containers/php/mount:/mount/:Z,ro
      - ./mail/.:/var/www/:rw
    networks:
      - mailnet

  if_ms_mysql:
    image: mysql:8
    restart: always
    container_name: cf_ms_mysql
    networks:
      - mailnet
    working_dir: /queries
    volumes:
      - ./.ms/mysql:/var/lib/mysql/:z,rw
      - ./.ms/mysql-queries:/queries:z,rw
      - ./containers/mysql/config.cnf:/etc/config.cnf
      - ./containers/mysql/copy.sh:/etc/copy.sh
      - mysql-data:/var/lib/mysql
    env_file:
      - ./.env

  if_ms_nginx:
    build:
      context: ./containers/nginx
      dockerfile: web.Dockerfile
    image: if_ms_nginx
    restart: always
    container_name: cf_ms_nginx
    networks:
      - mailnet
    ports:
      - ${FROXLOR_PORT}:80
      - ${ROUNDCUBE_PORT}:8080
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/sites-enabled:/etc/nginx/sites-enabled:rw
      - ./mail/.:/var/www/:rw


name: mail_serve

volumes:
  redis_cache:
  mysql-data:

networks:
  mailnet:
    driver: bridge
  appnet:
    driver: bridge
