name: mail_serve

volumes:
  redis_cache:

networks:
  mailnet:
    driver: bridge
  appnet:
    driver: bridge

services:
  if-ms-redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    container_name: cf-ms-redis
    networks:
      - mailnet
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_cache:/data
    profiles: [ "dev", "prod" ]

  if-ms-php-82:
    build:
      args:
        user: ${SYSUSER:-ubuntu}
        uid: 1000
      context: ./containers/php/8.2
      dockerfile: Dockerfile
    image: if-ms-php-82
    container_name: cf-ms-php-82
    restart: always
    working_dir: /var/www/
    env_file:
      - ./.env
    volumes:
      - ./containers/php/mount:/mount/:Z,ro
      - ./mail/.:/var/www/:rw
    networks:
      - mailnet
    profiles: [ "dev", "prod" ]

  if-ms-php-83:
    build:
      args:
        user: ${SYSUSER:-ubuntu}
        uid: 1000
      context: ./containers/php/8.3
      dockerfile: Dockerfile
    image: if-ms-php-83
    container_name: cf-ms-php-83
    restart: always
    working_dir: /var/www/
    env_file:
      - ./.env
    volumes:
      - ./containers/php/mount:/mount/:Z,ro
      - ./mail/.:/var/www/:rw
    networks:
      - mailnet
    extra_hosts:
      - "mail.domain.com=127.81.60.93"
    profiles: [ "dev", "prod" ]

  if-ms-mysql:
    image: mysql:8
    restart: always
    container_name: cf-ms-mysql
    networks:
      - mailnet
    working_dir: /queries
    volumes:
      - ./.ms/mysql:/var/lib/mysql/:z,rw
      - ./.ms/mysql-queries:/queries:z,rw
      - ./containers/mysql/config.cnf:/etc/config.cnf
      - ./containers/mysql/copy.sh:/etc/copy.sh
    env_file:
      - ./.env
    profiles: ["dev"]

  if-ms-phpmyadmin:
   image: phpmyadmin
   container_name: cf-ms-phpmyadmin
   restart: unless-stopped
   env_file:
    - ./.env
   ports:
    - ${PHPMYADMIN_PORT}:80
   networks:
    - mailnet
   profiles: ["dev", "prod"]

  if-ms-nginx:
    build:
      context: ./containers/nginx
      dockerfile: web.Dockerfile
    image: if-ms-nginx
    restart: always
    container_name: cf-ms-nginx
    networks:
      - mailnet
    ports:
      - ${FROXLOR_PORT}:80
      - ${ROUNDCUBE_PORT}:8080
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/sites-enabled:/etc/nginx/sites-enabled:rw
      - ./mail/.:/var/www/:rw
    profiles: [ "dev", "prod" ]
  
